### ISSUE TITLE
some HarmonicSimilarities contain 4 ChordProgressions

### ISSUE THREAD

**Issue by phivk** [polifonia-project/KG_data_transformation#6]
see this example in the ttl file I am using for testing:
https://github.com/polifonia-project/KG_data_transformation/blob/d4a8a81ec975b8938f6741e88c2015952946a107/harmonic_sim_etl/kg/versions/polifonia-kg-harmonic-test.ttl#L73-L77

The HarmonicSimilarity `harm_sim_00424_00339` contains the following ChordProgessions:

- `00339_Fmaj#_G#5_C#`
- `00424_Fmaj_Cmaj_Fmaj`
- `00339_C#_F#5_C#`
- `00424_GmajB_Cmaj_GmajD`

I assume this encodes a similarity based on:

- `00339_Fmaj#_G#5_C#` <--harmonically similar to --> `00424_Fmaj_Cmaj_Fmaj`
- `00339_C#_F#5_C#` <--harmonically similar to --> `00424_GmajB_Cmaj_GmajD`

The problem with this is that, while creating annotations for the sonar demo, I have no way of telling whether `00339_Fmaj#_G#5_C#` is related to `00424_Fmaj_Cmaj_Fmaj` or `00424_GmajB_Cmaj_GmajD` (likewise for all other combinations).

I might be able to use the ordering of the ChordProgressions, but that feels brittle and hacky.

Could we consider restricting HarmonicSimiliarities to a single pair of ChordProgressions (at least for the time being)?
If so, should this be done at the stage of 
1) calculating HarmonicSimilarities @andreamust @jonnybluesman?
OR 
2) KG data transformation @delfimpandiani @ccolonna @FiorelaCiroku?
OR
3) am I missing something and I should be able to deal with this at the Sonar data transformation step?

**Comment by ccolonna** [comment]
Hey @phivk ,

you can look at this, the PR should close the issue.
https://github.com/polifonia-project/KG_data_transformation/pull/7#issue-1030185954

Now you have a link between related chord progression. In the PR there's the link to the ontology used to model data in the KG.

You can also see rules used [here](https://github.com/polifonia-project/KG_data_transformation/blob/master/harmonic_sim_etl/queries/harmonic-similarity-0.0.2.sparql#L24-L63) .

I close the issue for the moment in case you see something else feel free to reopen this or a new one.
